/** Contenu écrit autonome. Repères généraux, cas fictifs, sans conseil individuel. */
export const LECONS = [
  {
    cle: "e0", numero: 0, titre: "Avant de commencer", minutes: 5,
    resume: "Comprendre à quoi servent les sept erreurs et ce qu’elles ne décident pas à votre place.",
    aFaire: "Gardez à portée de main les dates et documents que vous connaissez déjà.",
    acquis: ["Comprendre l’objectif du guide", "Distinguer un repère général d’un conseil individuel"],
    videoIndex: -1, documents: [],
    blocs: [["Votre point de départ", "Ce guide vous aide à reconnaître sept erreurs avant qu’elles ne deviennent des questions urgentes pour vos enfants. Vous n’avez rien à signer ni à décider pendant la lecture. Chaque chapitre vous explique le mécanisme, vous montre un cas concret et vous indique les informations à retrouver."]],
  },
  {
    cle: "e1", numero: 1, titre: "Erreur 1 - Laisser passer le compteur des quinze ans", minutes: 10,
    resume: "Comprendre quand l’abattement parent-enfant a déjà été utilisé et quand il peut de nouveau s’appliquer.",
    aFaire: "Retrouvez, pour chaque don, le donateur, le bénéficiaire, la date, le montant et la déclaration.",
    acquis: ["L’abattement de 100 000 € se suit par parent et par enfant", "Une donation antérieure peut encore réduire l’abattement disponible"],
    videoIndex: -1, documents: [],
    blocs: [
      ["Ce que les gens ne savent pas", "Beaucoup de parents connaissent le chiffre de 100 000 €, mais ignorent qu’il se suit séparément pour chaque couple parent-enfant et sur une période de quinze ans. Un don ancien peut donc avoir consommé tout ou partie de l’abattement encore disponible. À l’inverse, attendre sans avoir jamais commencé peut empêcher d’utiliser plusieurs fois ce mécanisme au cours d’une vie."],
      ["Ce qu’il faut comprendre", "Chaque parent peut utiliser un abattement de 100 000 € pour chaque enfant, en une ou plusieurs fois sur quinze ans. Une donation de moins de quinze ans peut aussi peser sur l’abattement applicable à la succession. Le compteur fiscal ne remplace pas la question essentielle : pouvez-vous transmettre sans fragiliser votre propre sécurité ?"],
      ["Exemples concrets", "Cas 1 : un père a déclaré 60 000 € donnés à sa fille il y a huit ans. Dans ce schéma simplifié, il lui reste 40 000 € d’abattement ordinaire disponible pour elle pendant la période en cours. Cas 2 : les deux parents donnent chacun à leurs deux enfants. Il existe alors quatre suivis distincts, pas un compteur unique pour toute la famille. Cas 3 : un ancien transfert est retrouvé sans déclaration certaine ; sa date et sa qualification doivent être vérifiées avant tout nouveau calcul."],
      ["Comment l’appliquer à votre situation", "Faites une liste courte : qui a donné, à qui, quoi, combien, à quelle date et avec quel justificatif. Téléchargez les récépissés disponibles et séparez les dons de chaque parent. Faites confirmer l’historique et l’abattement restant avant une nouvelle opération. Ne donnez jamais pour respecter un calendrier si cela réduit l’argent ou les droits dont vous avez besoin pour vivre."],
    ],
  },
  {
    cle: "e2", numero: 2, titre: "Erreur 2 - Regarder l’âge du contrat au lieu de l’âge au moment des versements", minutes: 10,
    resume: "Comprendre pourquoi le 70e anniversaire change la lecture fiscale des versements d’assurance-vie.",
    aFaire: "Demandez l’historique daté des versements et la clause bénéficiaire actuellement enregistrée.",
    siNonConcerne: "Si vous n’avez pas d’assurance-vie, passez directement à l’erreur 3. Ce guide ne vous recommande pas d’ouvrir un contrat.",
    acquis: ["C’est la date de chaque versement qui compte", "152 500 € par bénéficiaire et 30 500 € au total ne sont pas le même abattement"],
    videoIndex: -1, documents: [],
    blocs: [
      ["Ce que les gens ne savent pas", "Un contrat peut avoir été ouvert longtemps avant 70 ans et recevoir pourtant des versements après cet âge. Le nom du produit et sa date d’ouverture ne suffisent donc pas. Beaucoup de familles découvrent aussi trop tard qu’une ancienne clause bénéficiaire ne correspond plus aux personnes qu’elles voulaient protéger."],
      ["Ce qu’il faut comprendre", "Pour les contrats concernés, les primes versées avant 70 ans relèvent notamment d’un abattement de 152 500 € par bénéficiaire, tous contrats du même assuré confondus. Après 70 ans, les primes concernées relèvent notamment d’un abattement global de 30 500 €, partagé entre les contrats et bénéficiaires. Les gains et les situations particulières demandent une lecture distincte : après 70 ans ne signifie pas que l’assurance-vie ne sert plus à rien."],
      ["Exemples concrets", "Cas 1 : un contrat ouvert à 55 ans reçoit 40 000 € à 68 ans. La date utile pour ce versement est 68 ans. Cas 2 : le même contrat reçoit ensuite 40 000 € à 72 ans ; ce second versement n’entre pas dans le même régime. Cas 3 : deux bénéficiaires sont désignés sur plusieurs contrats ; l’abattement de 30 500 € après 70 ans reste global, il n’est pas multiplié par le nombre de contrats ou de bénéficiaires."],
      ["Comment l’appliquer à votre situation", "Pour chaque contrat, demandez par écrit la clause bénéficiaire en vigueur, l’historique des versements avec leurs dates et les avenants. Classez les versements avant et après 70 ans sans essayer de recalculer seul la fiscalité finale. Vérifiez que les personnes désignées correspondent encore à votre intention, puis faites examiner toute modification avant de la signer."],
    ],
  },
  {
    cle: "e3", numero: 3, titre: "Erreur 3 - Découvrir trop tard le changement de valeur à 71 ans", minutes: 10,
    resume: "Comprendre le repère de 71 ans lorsque l’usufruit et la nue-propriété d’un bien sont séparés.",
    aFaire: "Retrouvez l’acte de propriété, la part de chaque propriétaire et l’âge exact de la personne qui conserverait l’usufruit.",
    acquis: ["La nue-propriété est évaluée à 60 % avant 71 ans puis à 70 % de 71 à 80 ans", "Le barème fiscal ne suffit pas à décider d’une donation"],
    videoIndex: -1, documents: [],
    blocs: [
      ["Ce que les gens ne savent pas", "Il est possible de donner la nue-propriété d’un logement tout en conservant l’usufruit, c’est-à-dire notamment le droit de l’occuper ou d’en percevoir les revenus. Mais la valeur fiscale de la nue-propriété avance par paliers avec l’âge de l’usufruitier. Le passage à 71 ans est l’un de ces paliers."],
      ["Ce qu’il faut comprendre", "Dans le barème fiscal de l’usufruit viager, la nue-propriété vaut 60 % lorsque l’usufruitier a de 61 à 70 ans, puis 70 % de 71 à 80 ans. Cela augmente la base transmise pour une même valeur de bien. Ce n’est toutefois qu’un élément : les frais, la propriété réelle, les pouvoirs de chacun, les travaux, une vente future et votre besoin de sécurité doivent aussi être examinés."],
      ["Exemple concret", "Un parent seul envisage la donation de la nue-propriété d’une maison estimée à 480 000 € à un enfant, avec un abattement de 100 000 € entièrement disponible. À 70 ans, la nue-propriété est évaluée à 288 000 € ; à 71 ans, à 336 000 €. Dans ce cas pédagogique simplifié, les 48 000 € de base supplémentaires produisent environ 9 600 € de droits supplémentaires au taux marginal de 20 %, hors frais et autres paramètres."],
      ["Comment l’appliquer à votre situation", "Vérifiez d’abord qui possède réellement le logement et dans quelles proportions. Notez l’âge exact de chaque usufruitier potentiel. Demandez au notaire un chiffrage écrit des scénarios avant et après le prochain palier, les frais de l’acte, les conséquences d’une vente et la répartition des charges. Ne signez pas uniquement parce qu’une date approche."],
    ],
  },
  {
    cle: "e4", numero: 4, titre: "Erreur 4 - Croire que le mariage, le PACS ou la vie commune règlent tout", minutes: 12,
    resume: "Séparer propriété, droit d’hériter et fiscalité pour éviter une protection de couple seulement supposée.",
    aFaire: "Retrouvez contrat de mariage, convention de PACS, testament, donation entre époux et acte d’achat.",
    acquis: ["Être exonéré ne signifie pas recevoir automatiquement", "La présence d’enfants non communs peut modifier les droits du conjoint"],
    videoIndex: -1, documents: [],
    blocs: [
      ["Ce que les gens ne savent pas", "Dire « nous avons toujours tout partagé » ne décrit pas ce que chacun possède ni ce que l’autre recevrait. Le conjoint marié est exonéré de droits de succession, mais il ne reçoit pas nécessairement tout. Le partenaire de PACS est exonéré fiscalement, mais il n’est pas héritier légal sans disposition. Le concubin ne bénéficie pas de la même protection."],
      ["Ce qu’il faut comprendre", "Trois questions doivent rester séparées : qui possède le bien aujourd’hui, qui a juridiquement le droit de recevoir, et quelle fiscalité s’applique à cette personne. Le régime matrimonial, la composition de la famille, un testament, une donation entre époux ou une clause d’attribution peuvent modifier la réponse. Une protection forte du survivant peut aussi reporter davantage de patrimoine sur le second décès."],
      ["Exemples concrets", "Cas 1 : un couple marié avec uniquement des enfants communs peut laisser au conjoint une option successorale prévue par la loi ; ce n’est pas automatiquement la pleine propriété de tout. Cas 2 : en présence d’un enfant non commun, les droits légaux du conjoint ne sont pas les mêmes. Cas 3 : un partenaire de PACS sans testament n’hérite pas automatiquement. Cas 4 : un enfant du conjoint non adopté peut être fiscalement traité très différemment d’un enfant en ligne directe."],
      ["Comment l’appliquer à votre situation", "Rassemblez les documents qui gouvernent votre couple et votre logement. Écrivez les liens exacts entre chaque adulte et chaque enfant. Posez au professionnel trois questions : que possède chacun aujourd’hui, que recevrait chacun si rien ne change, et que se passerait-il au premier puis au second décès ? Demandez une réponse qui distingue clairement les droits civils de l’impôt."],
    ],
  },
  {
    cle: "e5", numero: 5, titre: "Erreur 5 - Faire un don sans créer une trace exploitable", minutes: 10,
    resume: "Distinguer don manuel, présent d’usage et prêt familial, puis conserver la date et la preuve utiles.",
    aFaire: "Reconstituez l’historique des transferts familiaux sans inventer une date ou une qualification.",
    acquis: ["Un don manuel doit en principe être déclaré même s’il ne déclenche pas de droits", "La déclaration permet de conserver une date et un historique vérifiables"],
    videoIndex: -1, documents: [],
    blocs: [
      ["Ce que les gens ne savent pas", "Un virement entre proches peut être un don, un prêt, le remboursement d’une dépense ou un présent d’usage. Ces mots ne sont pas interchangeables. Depuis le 1er janvier 2026, la déclaration des dons manuels et dons de sommes d’argent se fait en principe en ligne, même lorsque l’abattement évite tout droit à payer."],
      ["Ce qu’il faut comprendre", "Déclarer un don ne signifie pas automatiquement payer un impôt. La déclaration fixe un historique utile pour le suivi des abattements et évite de laisser aux enfants un transfert impossible à expliquer. Les conséquences civiles d’un don peuvent toutefois rester distinctes de son traitement fiscal : le délai de quinze ans ne fait pas disparaître toutes les questions d’équilibre entre héritiers."],
      ["Exemples concrets", "Cas 1 : 10 000 € sont virés à un enfant pour l’aider à acheter. Si c’est un don, le bénéficiaire doit en principe le déclarer, même si aucun droit n’est dû. Cas 2 : 10 000 € sont prêtés et doivent être remboursés ; l’absence d’écrit peut créer un conflit sur leur nature. Cas 3 : un cadeau proportionné aux ressources est offert pour un événement ; sa qualification dépend du contexte, pas seulement du montant."],
      ["Comment l’appliquer à votre situation", "Listez chaque transfert important avec la date, le montant, le motif, le bénéficiaire et la preuve disponible. Ne rebaptisez pas après coup un don en prêt ou inversement. Retrouvez les déclarations dans l’espace fiscal du bénéficiaire et demandez comment traiter les cas incertains. Pour un bien immobilier, passez obligatoirement par un acte notarié."],
    ],
  },
  {
    cle: "e6", numero: 6, titre: "Erreur 6 - Oublier que les petits-enfants ont leurs propres règles", minutes: 10,
    resume: "Comprendre quand un petit-enfant peut recevoir et pourquoi donation et succession ne se confondent pas.",
    aFaire: "Écrivez qui vous souhaitez aider, à quel moment et sans compromettre l’équilibre avec vos enfants.",
    acquis: ["L’abattement de donation grand-parent/petit-enfant est distinct", "Un petit-enfant n’hérite pas toujours directement si son parent est vivant"],
    videoIndex: -1, documents: [],
    blocs: [
      ["Ce que les gens ne savent pas", "Aider directement un petit-enfant n’utilise pas nécessairement les mêmes abattements qu’aider son enfant. Mais un abattement applicable à une donation ne devient pas automatiquement un abattement de succession. Beaucoup de grands-parents mélangent ces deux moments et surestiment ce qui se produira sans disposition particulière."],
      ["Ce qu’il faut comprendre", "Un grand-parent peut notamment bénéficier d’un abattement de 31 865 € pour une donation à un petit-enfant, renouvelable selon la période légale. Un don familial de somme d’argent peut parfois s’ajouter sous des conditions d’âge et de majorité. Lors d’une succession, la place du petit-enfant dépend notamment de la situation de son parent et des dispositions prises."],
      ["Exemples concrets", "Cas 1 : une grand-mère souhaite aider un petit-enfant majeur maintenant ; elle doit distinguer l’abattement de donation et, si les conditions sont réunies, celui du don familial de somme d’argent. Cas 2 : elle suppose que ce petit-enfant recevra automatiquement à son décès alors que son propre enfant est vivant ; cette hypothèse doit être vérifiée. Cas 3 : plusieurs petits-enfants reçoivent des montants différents ; l’intention d’aide doit être rapprochée des droits des héritiers et des donations déjà faites. Repère temporaire : l’article 790 A bis prévoit, sous conditions, une exonération distincte pour certains dons de sommes d’argent réalisés du 15 février 2025 au 31 décembre 2026 et affectés dans les six mois à un logement neuf, une VEFA ou certains travaux de rénovation énergétique. Les plafonds annoncés sont de 100 000 € par donateur et bénéficiaire, dans une limite globale de 300 000 € reçus par bénéficiaire. Vérifiez toutes les conditions avant tout versement."],
      ["Comment l’appliquer à votre situation", "Dessinez simplement les générations et notez qui est vivant, qui est l’enfant de qui et les aides déjà données. Distinguez ce que vous voulez faire maintenant de ce que vous voulez prévoir au décès. Faites calculer séparément les abattements par donateur et bénéficiaire, puis vérifiez les conséquences civiles et l’équilibre entre les branches de la famille."],
    ],
  },
  {
    cle: "e7", numero: 7, titre: "Erreur 7 - Arriver chez le notaire avec une histoire incomplète", minutes: 10,
    resume: "Obtenir un rendez-vous utile en apportant les faits, les documents et les questions qui changent réellement l’étude.",
    aFaire: "Préparez une page avec votre famille, vos biens, vos dons passés et vos trois questions prioritaires.",
    acquis: ["Le notaire peut mieux étudier un dossier lorsque les faits essentiels sont disponibles", "Un rendez-vous doit se terminer par des réponses, des pièces manquantes et une prochaine action"],
    videoIndex: -1, documents: [],
    blocs: [
      ["Ce que les gens ne savent pas", "Le notaire ne peut pas deviner un don ancien, une clause d’assurance-vie, un enfant d’une autre union ou un document resté dans un tiroir. Si les faits essentiels apparaissent seulement à la fin du rendez-vous, l’étude peut devoir être reprise, des pièces redemandées et une échéance utile peut être manquée."],
      ["Ce qu’il faut comprendre", "Consulter un notaire reste indispensable pour un acte immobilier et utile pour sécuriser une situation individuelle. Ce guide ne le remplace pas : il vous évite d’utiliser le rendez-vous pour découvrir les notions les plus élémentaires. Vous arrivez avec un objectif précis, un inventaire compréhensible et les anomalies déjà repérées ; le professionnel peut alors consacrer son temps à votre cas."],
      ["Exemple concret", "Jean-Pierre arrive en disant seulement : « Je veux protéger mes enfants. » Le notaire doit d’abord reconstituer sa famille, ses titres de propriété et ses dons antérieurs. Martine apporte une page indiquant son régime matrimonial à confirmer, ses deux enfants dont un d’une précédente union, la maison, une donation de 2018 et trois questions. Son dossier n’est pas juridiquement résolu, mais le point de départ est immédiatement plus précis."],
      ["Comment l’appliquer à votre situation", "Préparez quatre rubriques : famille, biens et dettes, donations et contrats, questions. Demandez au cabinet quels documents transmettre, par quel canal sécurisé et quel sera le coût de l’étude ou des actes envisagés. Pendant le rendez-vous, notez ce qui est confirmé, ce qui manque, qui doit agir et à quelle date. Ne repartez pas avec une simple impression de tranquillité."],
    ],
  },
];
