import { SITE_URL } from "./config";
export type Etape = { cle: string; jour: number; levier: string; objet: (prenom: string) => string; corps: (prenom: string) => string[]; bouton: { texte: string; chemin: string }; ps?: string; };
export const SEQUENCE: Etape[] = [
{ cle: "j1", jour: 1, levier: "Rêve", objet: () => "« Papa, maman… vous aviez pensé à nous. »", corps: p => ["Bonjour " + p + ",", ...["Un dimanche, autour de la table. Les enfants parlent de leurs projets, les petits-enfants jouent dans le jardin. Vous regardez cette maison que vous avez mis des années à payer. Ce que vous voulez leur laisser n’est pas une énigme fiscale. C’est une histoire de famille qui continue.","Ce que vous aimeriez transmettre ne tient pas seulement dans un montant. Il y a la maison, bien sûr. Mais aussi la possibilité pour vos proches de retrouver les informations et de savoir à qui poser leurs questions.","Imaginez pouvoir leur dire : « J’ai commencé à préparer les choses. Voilà où sont les informations, voilà ce que je veux faire vérifier. » Pas une promesse de tout maîtriser. La fierté d’avoir fait un premier pas pour eux.","C’est le point de départ d’Héritage Intact : connaître les erreurs qui peuvent laisser vos proches seuls face aux questions et aux dates passées.","Pas besoin d’être fiscaliste. Pas besoin de décider d’une donation. Les 7 erreurs sont expliquées clairement et à l’écrit.","Le guide coûte 52 €, une seule fois. Ce soir, vous pouvez commencer par reconnaître la première erreur, plutôt que laisser une nouvelle inquiétude de côté."]], bouton: { texte: "Découvrir les 7 erreurs", chemin: "/methode" } },
{ cle: "j2", jour: 2, levier: "Excuser les échecs", objet: () => "Maison payée ne veut pas dire transmission préparée", corps: p => ["Bonjour " + p + ",", ...["Vous avez su travailler, rembourser la maison et aider vos enfants. Pourtant, ce dossier reste au fond du tiroir. Un article sur la donation, une vidéo sur l’assurance-vie, puis cette phrase : « Je vais attendre de mieux comprendre. »","Qui possède vraiment quoi ? Quels documents retrouver ? Par quel sujet commencer avec le notaire ?","Repousser un sujet qui mélange l’argent, la famille et la disparition n’est pas forcément manquer de volonté. Quand tout semble lié, il est difficile de choisir le premier geste.","Le piège n’est pas votre manque de volonté. C’est de collectionner des réponses générales sans savoir quelle question poser pour commencer. Les 7 erreurs vous donnent cet ordre : repérer, rassembler, faire vérifier.","Une priorité. Ce que vous savez déjà. Ce qui reste à faire confirmer. Ensuite seulement, les repères et les supports pour préparer la discussion.","Vous n’achetez pas des règles secrètes : les sources officielles sont publiques. Vous achetez une organisation pour les aborder dans un ordre compréhensible et préparer vos questions.","Si vous souhaitez arrêter de collectionner les onglets sans savoir quoi en faire, regardez les étapes du parcours. Le premier achat reste autonome : aucun complément n’est nécessaire pour le terminer."]], bouton: { texte: "Voir comment commencer", chemin: "/methode" } },
{ cle: "j3", jour: 3, levier: "Peur : ce qui ne se rattrape plus, puis la peur d’acheter levée", objet: p => p ? p + ", ce que personne ne pourra décider à votre place" : "Ce que personne ne pourra décider à votre place", corps: p => ["Bonjour " + p + ",", ...["Un matin, vos enfants ouvriront un tiroir. Ils y trouveront des relevés, un acte, peut-être un contrat d’assurance-vie signé il y a quinze ans. Et ils devront deviner ce que vous vouliez.","Deviner qui possédait quoi. Deviner si cette clause désigne encore la bonne personne. Deviner si l’aide versée à l’un d’eux comptait comme une donation, et ce qu’il faut en déclarer. Chaque supposition qu’ils feront à votre place sera une décision prise sans vous.","Et certaines de ces questions ne se rattrapent pas. Une clause bénéficiaire se relit tant que vous êtes là pour le faire. Un abattement se renouvelle avec le temps, mais le compteur ne repart jamais en arrière. Les repères liés à l’âge, notamment autour de 70 ans pour l’assurance-vie, ne s’appliquent pas rétroactivement.","Vous le savez déjà. C’est même pour cela que ce dossier revient vous chercher certains dimanches soir, avant de retourner au fond du tiroir.","Alors soyons clairs sur ce qui vous est demandé : rien. Héritage Intact ne vous demande ni de donner, ni de signer, ni de modifier un contrat. Les 7 erreurs vous montrent les sujets qui méritent une vérification avant toute décision. Votre logement, vos dépenses et vos projets passent avant toute économie d’impôt.","Si vous préférez prendre rendez-vous chez le notaire dès demain, faites-le. Les 7 erreurs servent justement à préparer vos questions et à arriver avec les bonnes informations.","Les 7 erreurs coûtent 52 €, en paiement unique. La garantie commerciale de 30 jours vous permet de les découvrir et de demander le remboursement selon les conditions présentées.","Ce soir, vous pouvez encore décider vous-même de ce qui doit être vérifié. C’est exactement ce que demande la première erreur."]], bouton: { texte: "Découvrir les 7 erreurs", chemin: "/methode" } },
{ cle: "j4", jour: 4, levier: "Confirmer les doutes et prouver", objet: () => "« Encore une formation… et après ? »", corps: p => ["Bonjour " + p + ",", ...["Une belle page ne prépare pas votre transmission. Et acheter des dizaines de vidéos pour les laisser de côté ne vous avancerait pas davantage. Vous avez raison d’exiger autre chose : savoir exactement ce que vous allez découvrir.","Les 7 erreurs mettent des mots sur les oublis, les dates et les suppositions qui peuvent peser sur votre famille.","La présentation ci-dessous montre leur impact avec un cas chiffré et des hypothèses visibles.","Vous n’avez pas besoin de connaître déjà les règles. Les sept erreurs sont expliquées à l’écrit, dans un ordre clair. Aucun tournage pédagogique n’est à attendre.","Le guide coûte 52 €, une seule fois. Vous achetez l’accès aux 7 erreurs, pas une promesse de tournage ni un espace vide.","Votre premier achat est autonome ; la garantie commerciale de 30 jours vous permet de découvrir le contenu à votre rythme.","Ce soir, vous pouvez encore garder ces questions dans votre tête. Ou découvrir les erreurs pendant que vous pouvez encore agir."]], bouton: { texte: "Découvrir les 7 erreurs", chemin: "/methode" } },
{ cle: "j5", jour: 5, levier: "Ennemi : personne n’est payé pour vous prévenir", objet: () => "Personne n’est payé pour vous prévenir", corps: p => ["Bonjour " + p + ",", ...["Une question que peu de gens se posent : autour de vous, qui a intérêt à ce que vous prépariez votre transmission maintenant ?","L’État encaisse les droits au moment de la succession. Votre banque est rémunérée sur les frais de votre contrat. Votre notaire est payé à l’acte, et l’acte arrive, le plus souvent, quand la succession est déjà ouverte. Aucun d’eux n’est malhonnête. Simplement, aucun d’eux n’est payé pour venir vous prévenir avant.","C’est ainsi qu’on peut signer un contrat il y a quinze ans sans que personne ne vous rappelle jamais d’en relire la clause. Qu’une aide versée à un enfant reste sans trace écrite pendant des années. Personne n’a menti. Personne n’a appelé non plus.","Le silence finit par passer pour une bonne nouvelle : la maison est payée, le contrat est signé, donc tout serait réglé. Et la première personne à ouvrir vraiment le dossier sera votre famille, le jour où vous ne serez plus là pour l’expliquer.","Et nous, pourquoi nous croire ? Pour une raison simple : nous ne vendons ni contrat, ni acte, ni placement. Nous n’avons rien à vous faire signer. Le guide cite ses sources, le Code général des impôts article par article, pour que vous puissiez les vérifier sans nous. Et il dit aussi ce qu’il ne fait pas : il ne remplace ni votre notaire, ni un conseil adapté à votre situation.","Ce qu’il fait tient en trois gestes, dans cet ordre : faire le point sur votre situation, rassembler les informations, puis faire vérifier les décisions par le professionnel de votre choix.","Ne laissez pas un article de plus rejoindre les autres sans suite. Ouvrez les 7 erreurs et transformez votre première inquiétude en question écrite. C’est une petite action ; c’est déjà la fin du « je ne sais pas par où commencer »."]], bouton: { texte: "Découvrir les 7 erreurs", chemin: "/methode" } },
{ cle: "j6", jour: 6, levier: "Closing : coût de l’attente, valeur et première action", objet: () => "Six mois pour payer. Ensuite, la facture grossit chaque mois.", corps: p => ["Bonjour " + p + ",", ...["Le jour où une succession s’ouvre, un délai commence. Les héritiers ont six mois pour déclarer la succession et payer les droits. En euros, pas en parts de maison.","Si l’épargne ne suffit pas, il faut trouver l’argent ailleurs : emprunter, ou vendre. Et une maison ne se vend pas toujours en six mois.","Passé ce délai, le fisc n’attend pas sans contrepartie. Dès le 7e mois, des intérêts de retard de 0,20 % s’ajoutent chaque mois. À partir du 13e mois, une majoration de 10 % tombe en plus. Dans un cas fictif où les droits atteignent 82 194 €, c’est 164 € de plus chaque mois, puis 8 219 € d’un coup.","Le paiement peut être étalé. Mais il faut le demander avec la déclaration, payer des intérêts et apporter une garantie, le plus souvent une hypothèque sur un bien de la succession. Pour garder la maison de leurs parents, vos enfants pourraient devoir la donner en garantie à l’État.","Rien de cela ne se règle le jour du décès. Tout se prépare avant, pendant que vous êtes là pour décider.","En paiement unique, les 7 erreurs vous montrent ce qui pèse sur cette facture et ce qu’il faut faire vérifier pendant qu’il est encore temps. Pour une succession déjà ouverte ou un délai qui court, contactez directement un professionnel.","La garantie commerciale de 30 jours reste applicable. Vous pouvez ouvrir votre accès ce soir et commencer par la première erreur."]], bouton: { texte: "Découvrir les 7 erreurs · 52 €", chemin: "/commander" } },
{ cle: "j7", jour: 7, levier: "Closing final : dernière fenêtre de prix et fin de la série", objet: p => p ? "Dernier message, " + p : "Dernier message de cette série", corps: p => ["Bonjour " + p + ",", ...["C’est le septième et dernier message de cette série. Après celui-ci, je ne reviendrai plus vous parler des 7 erreurs.","Il serait facile de le fermer en se disant « après les vacances ». Puis après les fêtes. Puis l’année prochaine. La maison sera toujours là. Les questions aussi. Les dates, elles, auront avancé.","Et le jour venu, vos enfants auront six mois pour payer les droits, en euros. Chaque mois de retard leur coûtera ensuite des intérêts, puis une majoration.","Ou bien, au prochain repas de famille, vous ne direz plus « il faudrait qu’on s’en occupe ». Vous direz : « J’ai commencé. Voilà ce que j’ai vérifié, voilà ce qui reste à faire confirmer. »","Il n’y a rien à décider ce soir. Il y a une première erreur à lire et une question à écrire. Dix minutes suffisent.","Les 7 erreurs se paient une seule fois, avec la garantie commerciale de 30 jours. Une réduction commerciale ne change pas vos droits fiscaux : le prix qui vous concerne, et sa date de fin s’il y en a une, figurent ci-dessous. Si un seuil vous concerne de près, contactez directement votre notaire.","Ouvrez la première erreur maintenant, pendant que vous pouvez encore en parler ensemble."]], bouton: { texte: "Découvrir les 7 erreurs", chemin: "/commander" } },
];
export const lien = (chemin: string) => `${SITE_URL}${chemin}`;

/**
 * QUAND ENVOYER LA PREMIÈRE ÉTAPE.
 *
 * La séquence démarre à l'inscription, mais pas dans la même seconde que
 * l'email de livraison : deux messages collés sur un domaine jeune est le
 * meilleur moyen de finir en indésirable (c'est la règle que porte `etapeDue`).
 * On remet donc J1 à Resend tout de suite, avec une heure de délivrance
 * différée — le déclenchement ne dépend d'aucun cron, et le lecteur reçoit deux
 * messages espacés.
 *
 * Le garde-fou d'horaire n'est pas cosmétique : l'avatar a entre 60 et 80 ans
 * (`strategie/02-avatar.md`). Un email qui arrive à 2 h du matin est ouvert au
 * réveil, dans le tas, ou pas ouvert du tout.
 *
 * Approximation acceptée : le recalage se fait par heures entières, donc les
 * minutes sont conservées, et un changement d'heure peut décaler d'une heure.
 * C'est une fenêtre de politesse, pas un horaire à la minute.
 */
export const DELAI_PREMIERE_ETAPE_H = 3;
const HEURE_OUVERTURE = 9;
const HEURE_FERMETURE = 20;

export function momentPremiereEtape(maintenant: Date = new Date()): Date {
  const cible = new Date(maintenant.getTime() + DELAI_PREMIERE_ETAPE_H * 3_600_000);
  // `formatToParts` et non `format` : en français, une heure seule se rend
  // « 08 h », et `Number("08 h")` vaut NaN — ce qui produisait une date de
  // programmation invalide, donc un email jamais délivré.
  const heureParis = Number(
    new Intl.DateTimeFormat("fr-FR", {
      timeZone: "Europe/Paris",
      hour: "2-digit",
      hour12: false,
    })
      .formatToParts(cible)
      .find((p) => p.type === "hour")?.value,
  );
  if (!Number.isFinite(heureParis)) return cible;
  if (heureParis >= HEURE_OUVERTURE && heureParis < HEURE_FERMETURE) return cible;
  const decalage =
    heureParis < HEURE_OUVERTURE
      ? HEURE_OUVERTURE - heureParis
      : 24 - heureParis + HEURE_OUVERTURE;
  return new Date(cible.getTime() + decalage * 3_600_000);
}
