import { Header,Footer } from "@/components/Chrome";
export const metadata={title:"Conditions des avantages de démarrage"};
export default function Page(){return <><Header minimal/><main className="wrap py-9"><h1 className="mb-6 text-3xl">Votre avantage de démarrage</h1>
<p className="mb-4">Chaque produit conserve le même contenu quel que soit le prix affiché. L’avantage dépend uniquement d’une date personnelle enregistrée ; il ne dépend ni du patrimoine ni des réponses données.</p>
<h2 className="my-4 text-xl">Les 7 erreurs</h2><p>Prix catalogue : 52 €. Au clic vers la commande : 50% de réduction pendant 5 minutes, soit 26 €. Ensuite : retour à 52 €. Le départ est enregistré une seule fois pour l’adresse email renseignée en amont. Le Dossier notaire facultatif coûte 17 €, sans remise.</p>
<p className="mt-3">Une seconde fenêtre, et une seule, peut être proposée dans le dernier email de la série d’information, à une personne qui n’a pas acheté et dont la première fenêtre est passée. Elle dure 58 minutes et démarre au clic sur le bouton de cet email, pas à sa réception. Elle ne peut être obtenue qu’une fois par adresse email : cliquer de nouveau, depuis un autre appareil ou depuis un message transféré, affiche la même heure de fin. Passé ce délai, le prix revient à 52 € et aucune autre fenêtre n’est ouverte.</p>
<h2 className="my-4 text-xl">Mon plan adapté à ma situation</h2><p>Prix habituel : 297 €. Lorsque l’aperçu personnalisé est préparé : 147 € pendant 10 minutes, puis dernière chance à 197 € pendant 5 minutes. Ensuite : retour à 297 €. Le guide assurance-vie est un produit distinct à 67 €, sans remise liée à cette fenêtre.</p>
<h2 className="my-4 text-xl">Dossier Testament</h2><p>Prix catalogue : 47 €. À la fin du questionnaire du Plan, il peut être ajouté pour 29 € au prix alors affiché pour le Plan, soit une économie réelle de 18 € sur ce dossier. L’option n’est pas précochée. Le dossier structure les volontés, les documents et les questions que le notaire pourra ensuite traduire dans la forme adaptée.</p>
<h2 className="my-4 text-xl">Un seul départ, des dates conservées</h2><p>Recharger la page, changer de navigateur ou modifier ses réponses ne relance pas la fenêtre. La seconde fenêtre décrite ci-dessus est la seule exception, elle est proposée à notre initiative et ne peut pas être demandée. Aucun abonnement et aucun avantage retirable en espèces.</p>
<h2 className="my-4 text-xl">Votre confirmation fait foi</h2><p>Si le palier change avant l’initialisation du paiement, vous devez confirmer le montant actualisé. Un paiement déjà initialisé conserve le montant expressément accepté. La garantie commerciale de 30 jours et les conditions d’accès immédiat sont détaillées dans les <a href="/cgv">CGV</a>. Cette offre commerciale ne constitue pas une échéance fiscale.</p>
</main><Footer/></>}
