import { Header,Footer } from "@/components/Chrome";
export const metadata={title:"Conditions des avantages de démarrage"};
export default function Page(){return <><Header minimal/><main className="wrap py-9"><h1 className="mb-6 text-3xl">Votre avantage de démarrage</h1>
<p className="mb-4">Le produit de base et les contenus des packs sont les mêmes pour tous. L’avantage porte sur le prix, selon une date enregistrée pour votre adresse email. Il ne dépend ni de votre patrimoine ni de vos réponses familiales.</p>
<h2 className="my-4 text-xl">Les 7 erreurs</h2><p>Prix catalogue : 52 €. Au clic vers la page de commande : 50% de réduction pendant 2 minutes, soit 26 €, puis 30% pendant les 8 minutes suivantes au titre de la dernière chance, soit 36,40 €. Ensuite : 52 €. Le départ est enregistré une seule fois pour l’adresse email renseignée en amont. Le délai ne commence pas sur la page de vente et ne repart pas à zéro. Dossier facultatif : 17 €, sans remise de démarrage.</p>
<h2 className="my-4 text-xl">Compléments</h2><p>Prix catalogue : Préparation 197 € au total ; Préparation avec assurance-vie 247 € au total ; assurance-vie seule 67 €. Les achats inclus réellement payés sont d’abord déduits. Une fois le questionnaire post-achat validé : réduction de 25% pendant 20 minutes, puis de 10% jusqu’à 48 heures après cette validation, sur le seul complément restant à payer. Ensuite : fin de cette réduction.</p>
<h2 className="my-4 text-xl">Un seul départ, des dates conservées</h2><p>Les trois compléments partagent la même fenêtre. Recharger, changer d’offre, de navigateur, se réinscrire avec la même adresse ou modifier ses réponses ne la relance pas. Le montant est arrondi au centime. Aucun abonnement, aucun avantage retirable en espèces. Les achats inclus ne perdent pas leur déduction à l’expiration.</p>
<h2 className="my-4 text-xl">Votre confirmation fait foi</h2><p>Si le palier change avant l’initialisation du paiement, vous devez confirmer le montant actualisé. Un paiement déjà initialisé conserve le montant expressément accepté. La garantie commerciale de 30 jours et les conditions d’accès immédiat sont détaillées dans les <a href="/cgv">CGV</a>. Cette offre commerciale ne constitue pas une échéance fiscale.</p>
</main><Footer/></>}
