// Synchronisation mécanique des documents de lecture avec les sources de production.
const fs=require("node:fs"),vm=require("node:vm"),ts=require("typescript");
function lire(file){
 const exports={};
 const code=ts.transpileModule(fs.readFileSync(file,"utf8"),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;
 vm.runInNewContext(code,{exports,require:p=>{if(p==="./config")return {SITE_URL:"https://www.heritageintact.fr",VIDEO:{formation:[]}};throw Error("Import inattendu : "+p);}});
 return exports;
}
const {SEQUENCE}=lire("src/lib/sequence.ts");
const {LECONS}=lire("src/lib/lecons.ts");
const {OUVERTURES_CHAPITRES}=lire("src/lib/editorial-produits.ts");
let email="# Emails de production — V8\n\n9 septembre 2026. Les sept corps ci-dessous sont exportés de src/lib/sequence.ts. Leur envoi, leur prix et leur lien sont construits par src/lib/email.ts. Aucune campagne activée ou envoyée durant la recette.\n\n## Architecture CEO\n\nJ1 rêve ; J2 excuser le blocage ; J3 réduire la peur ; J4 répondre aux doutes avec une preuve d’usage ; J5 obstacle réel ; J6 valeur, objection, risque et action ; J7 clôture de la série. Chaque email commercial mène à un achat possible ; les messages de service délivrent l’accès sans y cacher une vente. Adaptation du process Valère, pas une validation de sa part.\n\n## Prix et urgence réellement injectés\n\nLe pied de chaque email commercial est calculé au moment de l’envoi : pourcentage encore actif, prix actuel et fin exacte du palier en heure de Paris. Le lien personnel reprend la date de départ enregistrée, même dans un autre navigateur ; il ne relance pas l’offre. Un email lu plus tard peut afficher un ancien prix : le site réaffiche le prix actuel avant confirmation.\n\nGuide : prix catalogue 52 €. Au clic vers la commande : 26 € pendant 2 minutes (−50 %), puis 36,40 € pendant 8 minutes (−30 %), puis 52 €. Aucun palier ne court sur la page de vente. La séquence quotidienne commence à J1 et ne prétend pas qu’un palier court avant le clic. Les liens de commande passent par /commander afin de démarrer une seule fenêtre personnelle ; les autres rejoignent la présentation. Le bouton final est remplacé par « Commencer les 7 erreurs maintenant · [prix actuel] ». Aucun faux compte à rebours dans un email figé.\n\nLes prix de 52 € dans les textes désignent le tarif catalogue. Les mentions de remise n’apparaissent que si une date valide existe. Le prix de référence et la présentation des pourcentages restent à faire relire avant publication.\n\n## J0 — lien de présentation demandé\n\nMessage de service immédiat, distinct du consentement commercial. Il conserve le lien personnel sans rallumer le compteur. L’email d’accès au contenu acheté ne dépend pas du consentement marketing.\n";
for(const e of SEQUENCE)email+="\n## "+e.cle.toUpperCase()+" — "+e.levier+"\n\nObjet : "+e.objet("[Prénom]")+"\n\n"+e.corps("[Prénom]").join("\n\n")+"\n\nCTA commercial : Commencer les 7 erreurs · [prix recalculé à l’envoi]. Destination personnelle : /reprendre/[jeton] si l’offre existe ; sinon "+e.bouton.chemin+".\n";
email+="\n## Après achat : livraison et accompagnement\n\nLes prospects ayant un accès acheté sortent de la séquence J1–J7. Reçu, accès et aide à la première fiche restent des messages de service, pas des emplacements publicitaires. Les achats et remboursements sont revérifiés avant recommandation.\n\n## Compléments — deux messages ciblés\n\nSource : envoyerComplement dans src/lib/email.ts, déclenchement dans sequence-ltv.ts et le cron.\n\nPremier objet : « Vous avez commencé pour eux. Préparez maintenant la suite. »\n\nOuverture : « Imaginez votre prochain échange : vous n’ouvrez plus trois tiroirs pour retrouver une information. Vous ouvrez votre préparation, avec ce qui est connu, ce qui manque et les questions propres à votre famille. C’est la suite de votre première fiche. »\n\nRappel : « Ne laissez pas votre première avancée sans suite ». Il rappelle la pièce, les questions et le suivi à terminer, sans faire passer l’accès déjà payé pour un avantage qui expire.\n\nVersion préparation : fiches familiales, trames et atelier pour préparer le rendez-vous puis conserver les réponses. Version assurance-vie : clause en vigueur, informations manquantes et demande à l’assureur.\n\nLe message donne le nom du seul complément retenu, les achats inclus réellement déduits et le montant restant. Puis il traite les objections : contenus déjà payés non refacturés ; pas de débit au clic dans l’email ; guides écrits à suivre ; garantie de 30 jours selon CGV ; base autonome.\n\nBouton : « Préparer la suite · [montant actuel] », vers la confirmation de l’espace. Aucun produit déjà possédé n’est proposé.\n\n### Déclenchement et protection de la réception\n\n- Consentement marketing explicite, absence de désinscription, accès non révoqué et première fiche terminée.\n- Premier complément à partir de J10 ; rappel à partir de J17 et au moins sept jours après le premier envoi réel ; arrêt à J35. Deux envois maximum, pas de cascade après refus ou plainte.\n- L’offre immédiate est sur le site juste après qualification et livraison ; d’autres points d’entrée se trouvent après la première fiche et dans les étapes maison/contrat. Ces emails tardifs servent la reprise, pas un faux rappel de la réduction de 48 heures déjà terminée.\n- Un seul message commercial éligible par passage, priorité au service, plafonds, clés anti-doublon, suppressions sur rebonds/plaintes et désinscription.\n- Activation séparée : EMAIL_MARKETING_ACTIVE et EMAIL_LTV_ACTIVE. Configuration, DNS et boîtes réelles restent à tester avant activation.\n\nLa qualité de réception se mesure ; aucune délivrabilité parfaite ni progression de LTV n’est démontrée par ces tests locaux.\n";
fs.writeFileSync("strategie/refonte-v2/05-EMAILS.md",email);
let produit="# Les 7 erreurs — contenu écrit de production V9\n\nExport du 9 septembre 2026 depuis src/lib/lecons.ts. Aucun tournage pédagogique. Le guide PDF ajoute les introductions et les fiches utiles ; l’espace utilise ces mêmes textes. Les huit blocs de quiz ont été retirés.\n";
for(const l of LECONS){
 produit+="\n## "+l.titre+"\n\n"+OUVERTURES_CHAPITRES[l.cle]+"\n\nCe que vous allez comprendre :\n\n"+l.acquis.map(a=>"- "+a).join("\n")+"\n";
 for(const [t,b] of l.blocs)produit+="\n### "+t+"\n\n"+b+"\n";
 produit+="\nAction : "+l.aFaire+"\n\nSupports : "+l.documents.join(", ")+".\n";
 if(l.siNonConcerne)produit+="\n"+l.siNonConcerne+"\n";
}
fs.writeFileSync("strategie/refonte-v2/03-PRODUIT-ECRIT.md",produit);
console.log("Documents synchronisés : 7 emails commerciaux et 8 étapes écrites.");
